#Ecosystem config file for PM2 to run the components of the NEMO Sargassium Operational Forecast System

apps:

  - script          : ./workers/download_weather.py
    name            : 'download_weather'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    autorestart     : false
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/process_forcing.py
    name            : 'process_forcing'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/run_nemo.py
    name            : 'run_nemo'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/watch_nemo.py
    name            : 'watch_nemo'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/get_sargassium.py
    name            : 'get_sargassium'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    autorestart     : false
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/find_seed.py
    name            : 'find_seed'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/v5Belize_Parcels.py
    name            : 'run_parcels'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/PlotParcelsOutput.py
    name            : 'plot_tracks'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/make_plots.py
    name            : 'make_plots'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/ftp_upload.py
    name            : 'ftp_upload'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 600000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'

  - script          : ./workers/scheduler.py
    name            : 'scheduler'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'


  - script          : ./workers/clean_up.py
    name            : 'clean_up'
    cwd             : '/work/thopri/BLZ-SURGE'
    args            : '-- config/nowcast.yaml'
    watch           : false
    restart_delay   : 86400000
    log_date_format : 'YYYY-MM-DD HH:mm:ss.SSS'
