# System configuration file for Nowcast system

# TODO put paths into one section and migrate to one work dir string
#PATHS:
#      work_dir: /home/thopri/BLZ-SURGE
#      config_dir: /config
#      status_dir: /config
#      grib_dir: /grib
#      netcdf_dir: /netcdf
#      container_work_dir: /BLZ-SURGE
#      netcdf_cont_dir: /netcdf
#      namelist_cont_dir: /namelist
#      weights_cont_dir: /weights
#      container_log: /logs
#MODEL:
#      container_name

#Download Weather worker configuration
weather:
  download:
    # West Longitude limit
        leftlon: -90
    # East Longitude limit
        rightlon: -82
    # North Latitude limit
        toplat: 22
    # Bottom Latitude limit
        bottomlat: 15
    # varaible 1
        var1: var_MSLET
    # variable 2
        var2: var_UGRD
    # variable 3
        var3: var_VGRD
    # Level to download data (10 m above ground)
        lev1: lev_10_m_above_ground
    # Level to download data (msl)
        lev2: lev_mean_sea_level
    # URL template from which to download NOAA NCEP Grid filter files for GFS model
        url_template: 'https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25_1hr.pl?file={file_name}{hours}&{lev1}=on&{lev2}=on&{var1}=on&{var2}=on&{var3}=on&subregion=&leftlon={leftlon}&rightlon={rightlon}&toplat={toplat}&bottomlat={bottomlat}&dir=%2{run_time}'
  # Template for GFS model file name
    # **Must be quoted to project {} characters**
        file_template: 'gfs.t{model_run}z.prgb2.0p25.f'
    # Number of hours requested in the forecast Goes upt 120 (I think)
        forecast_hrs: 120
    # Destination directory for downloaded GFS model GRIB data files
        dest_dir: '/home/thopri/BLZ-SURGE/grib/'
        status_dir: /home/thopri/BLZ-SURGE/config/

#Forcing process worker configuration
forcing:
  process:
    #number of forecast hours should be the same as in weather download
        forecast_hrs: 120
    #variable one
        var1: u10
    #variable description for netcdf file
        var1_des: 10 metre U wind component
    #varaible two
        var2: v10
    #variable description for netcdf file
        var2_des: 10 metre V wind component
    #variable three
        var3: msl
#    #variable description for netcdf file
#        var3_des: Pressure reduced to MSL
#    #Template of GRIB file names
#        file_template: '202011170000_arw_wrfout_d02.grb2'
    #variable description for netcdf file
        var3_des: MSLP (Eta model reduction)
    #Template of GRIB file names
        file_template: 'gfs.t{model_run}z.pgrb2.0p25.f'
    #Destination directory of NetCDF files
        netcdf_dest_dir: '/home/thopri/BLZ-SURGE/netcdf/GFS/'
    #Grib downloaded files location
        grib_dir: '/home/thopri/BLZ-SURGE/grib/'
    #Config name NOTE: do NOT use - in the name as it will break parsing of file names
        netcdf_name: BLZ-SURGE
        config_dir: /home/thopri/BLZ-SURGE/config/
        pm2log: /home/thopri/.pm2/pm2.log

#Generate Boundary worker configuration
generate:
  boundary:
    #name of template bilinear namelist file
        template_1: 'namelist_reshape_bilin_atmos_template'
    #name of template bicubic namelist file
        template_2: 'namelist_reshape_bicubic_atmos_template'
    #namelist file name for bilinear
        file_out_1: 'namelist_reshape_bilin_atmos'
    #namelist file name for bicubic
        file_out_2: 'namelist_reshape_bicubic_atmos'
    #keys to identify populate fields in namelist templates
        input_key_1: 'input_key_1'
        input_key_2: 'input_key_2'
    #destination directories for netcdf, namelist files and output weighted files
        netcdf_dest_dir: '/BLZ-SURGE/netcdf/'
        namelist_dir: '/BLZ-SURGE/namelist/'
        weights_dir: '/BLZ-SURGE/weights/'

#Run Nemo worker configuration
RUN_NEMO:
  # NEMO run duration
        duration: 120  # hours
  # Directory where files (e.g. namelist.time) and symlinks
  # (e,g. iodef.xml) necessary to prepare the NEMO runs are stored
        config_dir: /home/thopri/BLZ-SURGE/RUN_NEMO/
  #weighting file location
        weights_dir: /home/thopri/BLZ-SURGE/weights/
  #netcdf file location
        netcdf_dir: /home/thopri/BLZ-SURGE/netcdf/GFS/
  #location of boundary data for model
        boundary_dest: /home/thopri/BLZ-SURGE/RUN_NEMO/fluxes/
  #location of restart files
        restart_dir: /home/thopri/BLZ-SURGE/RUN_NEMO/Restart_files/
  #name of namelist template file
        namelist_template: 2_namelist_cfg_template
  #name of populated namelist file for model
        pop_namelist: namelist_cfg
  #name of variables for namelist file
        var1: .*u10
        var2: .*v10
        var3: .*msl
  #Time step of model in seconds.
        time_step : 1 #in seconds (6 mins)
  # Name of the NEMO configuration;
        config_name: BLZ-SURGE
   # Use restart file or not
        restart: false
  # restart interval (same as atmo model frequency)
        restart_int: 24 #hours
  # Name of the model domain coordinates file.
  # It is assumed to be in the EXP00/ directory of the NEMO configuration
  # directory composed from the "NEMO code" and "config name" keys above.
        coordinates: coordinates.nc
## Directory where run results are stored
        results archive: /home/thopri/BLZ-SURGE/RUN_NEMO/
  # Which container framework to use
        container: podman
        container_name: docker.io/thopri/nemo-surge:8814
        container_mount: /home/thopri/BLZ-SURGE/
        container_dir: BLZ-SURGE
  # Time to start model, starting at midnight fails due to no previous day data
        hour_start: '01' # 1 am
  # where to save container terminal output in log file
        container_log: /home/thopri/BLZ-SURGE/logs/
        status_dir: /home/thopri/BLZ-SURGE/config/
        pm2log: /home/thopri/.pm2/pm2.log

#Watch NEMO worker configuration
WATCH_NEMO:
    #location of model results directory
        results_dir: /home/thopri/BLZ-SURGE/RUN_NEMO/
    #duration of model run
        duration: 120 #Hours
    #time step of model
        time_step: 1 #In seconds (7.5 mins)
    #name of NEMO model configuration
        config_name: BLZ-SURGE
    # name of container to watch
        container_name: docker.io/thopri/nemo-surge:8814
        status_dir: /home/thopri/BLZ-SURGE/config/
        WATCH_INTERVAL: 1 # minutes
        pm2log: /home/thopri/.pm2/pm2.log
        output_dir: /home/thopri/BLZ-SURGE/OUTPUTS/netcdf
        file_parse:  'BLZ-SURGE_1h_*.nc'

#Make Plots NEMO worker configuration
make:
  plots:
    #location of station list file
        station_dir: /SRC/config/
    #location to save processed image plots both spatial and timeseries
        plots_dir: /SRC/output/plots/
    #location to save images to make gif animation
        animation_plots_dir: /SRC/output/plots/animation_plots/
    #location of output NETCDF directory
        netcdf_dir: /SRC/output/netcdf/
    #location of model outputs
        model_output_dir: /SRC/NEMOGCM/CONFIG/TEST/EXP00/
    #location to save CSV output
        csv_dir: /SRC/output/csv/
    #model time step    
        time_step: 1 #In seconds (6 mins)
    #total time of model run (hours)
        total_time: 120
    #interval for spatial plots e.g. every 12 hours
        interval: 10 #timesteps 10 time steps at 6 mins = 1 hour
    #global threshold to check across whole domain (currently not active)
        global_thres: 0.2
    #name of station list file
        station_list: station_list.txt
    #name of NEMO model configuration
        config_name: BLZ-SURGE

#Seeding Open Parcels worker configuration
GET_SAR:
    # URL
        url_template: 'https://optics.marine.usf.edu/subscription/modis/YUCATAN/{year}/comp/'
    # Produce plots? For QA and setup purposes.
        plot: False
    # projection for transforming data or giving it a projection?
        crs: '+proj=longlat'
    # limits of the domain
        north: 22
        south: 15
        east: -82
        west: -90
    # sargassum levels? note values are > or <
        min: 0
        max: 252
    # bathy meter location
        bathy_meter: '/home/thopri/BLZ-SURGE/INPUTS/BLZE12_bathy_meter.nc'
        coordinates: '/home/thopri/BLZ-SURGE/INPUTS/BLZE12_coordinates.nc'
    # directory to store downloaded product
        dest_dir: '/home/thopri/BLZ-SURGE/sargassium/'
    # name of GeoTiff image (processed from downloaded image)
        tiff_name: 'SargassoT7.tif'
    # string to parse correct image, i.e. unique part of filename
        parse_ID: 'DENSITY.png'
        status_dir: /home/thopri/BLZ-SURGE/config/

FIND_SEEDS:
      # name of GeoTiff image (processed from downloaded image)
      tiff_name: 'SargassoT7.tif'
      # directory to store downloaded product
      dest_dir: '/home/thopri/BLZ-SURGE/sargassium/'
      # Produce plots? For QA and setup purposes.
      plot: False
      bathy_meter: '/home/thopri/BLZ-SURGE/INPUTS/BLZE12_bathy_meter.nc'
      file_parse:  'C*DENSITY.png'
      pm2log: /home/thopri/.pm2/pm2.log

RUN_PARCELS:
        lon_csv: '/home/thopri/BLZ-SURGE/sargassium/ilon.csv'
        lat_csv: '/home/thopri/BLZ-SURGE/sargassium/ilat.csv'
        data_path: '/home/thopri/BLZ-SURGE/OUTPUTS/netcdf/'
        ufile_parse: 'BLZ-SURGE_1h_*U.nc'
        vfile_parse: 'BLZ-SURGE_1h_*V.nc'
        file_parse:  'BLZ-SURGE_1h_*.nc'
        grid_file: '/home/thopri/BLZ-SURGE/INPUTS/BLZE12_coordinates.nc'
        out_file: 'nBelize_nemo_sargaso_particlesT2'
        out_dir: '/home/thopri/BLZ-SURGE/OUTPUTS/tracks/'
        status_dir: '/home/thopri/BLZ-SURGE/config/'
        pm2log: /home/thopri/.pm2/pm2.log

PLOT_TRACKS:
        pm2log: /home/thopri/.pm2/pm2.log
        out_dir: '/home/thopri/BLZ-SURGE/OUTPUTS/plots/'
        plot_name_template:
        input_file_template: 'nBelize_nemo_sargaso_particlesT2.nc'
        input_dir: '/home/thopri/BLZ-SURGE/OUTPUTS/tracks/'
        num_particles: 500

#Clean up worker configuration
clean:
      up:
    #location of model run directory
        run_dir: /home/thopri/BLZ-SURGE/RUN_NEMO/
    #location of log files
        forcing_dir: /home/thopri/BLZ-SURGE/netcdf/
    #location of output files
        out_dir: /home/thopri/BLZ-SURGE/OUTPUTS/
    #name of model configuration
        config_name: BLZ-SURGE
    #location of restart files
        restart_dir: /home/thopri/BLZ-SURGE/RUN_NEMO/Restart_files/
    #Runtime model files to delete after successful run
        del_1: layout.dat
        del_2: namelist_cfg
        del_3: ocean.output
        del_4: output.namelist.dyn
        del_5: solver.stat
        del_6: time.step
    #number of days to keep output files
        num_days: 7
    # number of days to keep container logs
        log_days: 7
    #sub directories for forcing files to trim
        sub_1: GFS/
        sub_2: MBLZ/
    #sub directories for log files to trim
        log_dir: /home/thopri/BLZ-SURGE/logs/
    # Sargassium dir to trim
        sargassium_dir: /home/thopri/BLZ-SURGE/sargassium/
    #subdirectories for processed model output
        out_1: tracks/
        out_2: netcdf/
        out_3: plots/
